# Generated by Django 4.2.7 on 2023-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_id_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id_payment',
            field=models.CharField(null=True, verbose_name='id-платежа'),
        ),
    ]
